# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=hub.models.upload_path_handler),
        ),
    ]
