# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20160609_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='commit_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
