# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_file_commit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='repo',
            field=models.CharField(default='matts%20repo', max_length=100),
            preserve_default=False,
        ),
    ]
