# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_file_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='repo',
            field=models.CharField(default='matts repo', max_length=100),
        ),
    ]
